
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "UltraCRM_Webservice", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://192.168.99.112:81/UltraCRM_Webservice.asmx?wsdl")
public class UltraCRMWebservice
    extends Service
{

    private final static URL ULTRACRMWEBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://192.168.99.112:81/UltraCRM_Webservice.asmx?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ULTRACRMWEBSERVICE_WSDL_LOCATION = url;
    }

    public UltraCRMWebservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UltraCRMWebservice() {
        super(ULTRACRMWEBSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "UltraCRM_Webservice"));
    }

    /**
     * 
     * @return
     *     returns UltraCRMWebserviceSoap
     */
    @WebEndpoint(name = "UltraCRM_WebserviceSoap")
    public UltraCRMWebserviceSoap getUltraCRMWebserviceSoap() {
        return (UltraCRMWebserviceSoap)super.getPort(new QName("http://tempuri.org/", "UltraCRM_WebserviceSoap"), UltraCRMWebserviceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UltraCRMWebserviceSoap
     */
    @WebEndpoint(name = "UltraCRM_WebserviceSoap")
    public UltraCRMWebserviceSoap getUltraCRMWebserviceSoap(WebServiceFeature... features) {
        return (UltraCRMWebserviceSoap)super.getPort(new QName("http://tempuri.org/", "UltraCRM_WebserviceSoap"), UltraCRMWebserviceSoap.class, features);
    }

}
