
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UltraCRM_WebserviceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UltraCRMWebserviceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "VMS_Recv", action = "http://tempuri.org/VMS_Recv")
    @WebResult(name = "VMS_RecvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "VMS_Recv", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VMSRecv")
    @ResponseWrapper(localName = "VMS_RecvResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VMSRecvResponse")
    public String vmsRecv(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strCaller
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get_Caller_Area", action = "http://tempuri.org/Get_Caller_Area")
    @WebResult(name = "Get_Caller_AreaResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Caller_Area", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCallerArea")
    @ResponseWrapper(localName = "Get_Caller_AreaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCallerAreaResponse")
    public String getCallerArea(
        @WebParam(name = "strCaller", targetNamespace = "http://tempuri.org/")
        String strCaller);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fax_Sent", action = "http://tempuri.org/Fax_Sent")
    @WebResult(name = "Fax_SentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Fax_Sent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FaxSent")
    @ResponseWrapper(localName = "Fax_SentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FaxSentResponse")
    public String faxSent(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Fax_Recv", action = "http://tempuri.org/Fax_Recv")
    @WebResult(name = "Fax_RecvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Fax_Recv", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FaxRecv")
    @ResponseWrapper(localName = "Fax_RecvResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FaxRecvResponse")
    public String faxRecv(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strFile3
     * @param strFax
     * @param strGhid
     * @param strFile1
     * @param strStime
     * @param strFile2
     * @param strUname
     * @param strSubj
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Send_Fax", action = "http://tempuri.org/Send_Fax")
    @WebResult(name = "Send_FaxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Send_Fax", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendFax")
    @ResponseWrapper(localName = "Send_FaxResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendFaxResponse")
    public int sendFax(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strStime", targetNamespace = "http://tempuri.org/")
        String strStime,
        @WebParam(name = "strUname", targetNamespace = "http://tempuri.org/")
        String strUname,
        @WebParam(name = "strSubj", targetNamespace = "http://tempuri.org/")
        String strSubj,
        @WebParam(name = "strFax", targetNamespace = "http://tempuri.org/")
        String strFax,
        @WebParam(name = "strFile1", targetNamespace = "http://tempuri.org/")
        String strFile1,
        @WebParam(name = "strFile2", targetNamespace = "http://tempuri.org/")
        String strFile2,
        @WebParam(name = "strFile3", targetNamespace = "http://tempuri.org/")
        String strFile3,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Sms_Sent", action = "http://tempuri.org/Sms_Sent")
    @WebResult(name = "Sms_SentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Sms_Sent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SmsSent")
    @ResponseWrapper(localName = "Sms_SentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SmsSentResponse")
    public String smsSent(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Sms_Recv", action = "http://tempuri.org/Sms_Recv")
    @WebResult(name = "Sms_RecvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Sms_Recv", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SmsRecv")
    @ResponseWrapper(localName = "Sms_RecvResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SmsRecvResponse")
    public String smsRecv(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strBody
     * @param strGhid
     * @param strStime
     * @param strTelTo
     * @param strUname
     * @param strSubj
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Send_Sms", action = "http://tempuri.org/Send_Sms")
    @WebResult(name = "Send_SmsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Send_Sms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSms")
    @ResponseWrapper(localName = "Send_SmsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSmsResponse")
    public int sendSms(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strStime", targetNamespace = "http://tempuri.org/")
        String strStime,
        @WebParam(name = "strUname", targetNamespace = "http://tempuri.org/")
        String strUname,
        @WebParam(name = "strSubj", targetNamespace = "http://tempuri.org/")
        String strSubj,
        @WebParam(name = "strTel_To", targetNamespace = "http://tempuri.org/")
        String strTelTo,
        @WebParam(name = "strBody", targetNamespace = "http://tempuri.org/")
        String strBody,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Email_Sent", action = "http://tempuri.org/Email_Sent")
    @WebResult(name = "Email_SentResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Email_Sent", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmailSent")
    @ResponseWrapper(localName = "Email_SentResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmailSentResponse")
    public String emailSent(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Email_Recv", action = "http://tempuri.org/Email_Recv")
    @WebResult(name = "Email_RecvResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Email_Recv", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmailRecv")
    @ResponseWrapper(localName = "Email_RecvResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EmailRecvResponse")
    public String emailRecv(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param caller
     * @param userid
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get_Customer_Info", action = "http://tempuri.org/Get_Customer_Info")
    @WebResult(name = "Get_Customer_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Customer_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerInfo")
    @ResponseWrapper(localName = "Get_Customer_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCustomerInfoResponse")
    public String getCustomerInfo(
        @WebParam(name = "Caller", targetNamespace = "http://tempuri.org/")
        String caller,
        @WebParam(name = "Userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName);

    /**
     * 
     * @param userid
     * @param userName
     * @param strCaller
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get_Person_Info", action = "http://tempuri.org/Get_Person_Info")
    @WebResult(name = "Get_Person_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Person_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonInfo")
    @ResponseWrapper(localName = "Get_Person_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPersonInfoResponse")
    public String getPersonInfo(
        @WebParam(name = "strCaller", targetNamespace = "http://tempuri.org/")
        String strCaller,
        @WebParam(name = "Userid", targetNamespace = "http://tempuri.org/")
        String userid,
        @WebParam(name = "UserName", targetNamespace = "http://tempuri.org/")
        String userName);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @param strCallid
     * @param strCaller
     * @param strExt
     * @param strDirection
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get_Talentel_log_Info", action = "http://tempuri.org/Get_Talentel_log_Info")
    @WebResult(name = "Get_Talentel_log_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Talentel_log_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTalentelLogInfo")
    @ResponseWrapper(localName = "Get_Talentel_log_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTalentelLogInfoResponse")
    public String getTalentelLogInfo(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strCaller", targetNamespace = "http://tempuri.org/")
        String strCaller,
        @WebParam(name = "strExt", targetNamespace = "http://tempuri.org/")
        String strExt,
        @WebParam(name = "strCallid", targetNamespace = "http://tempuri.org/")
        String strCallid,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid,
        @WebParam(name = "strDirection", targetNamespace = "http://tempuri.org/")
        String strDirection);

    /**
     * 
     * @param strSdate
     * @param strEdate
     * @param strGhid
     * @param strCallid
     * @param strCaller
     * @param strExt
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get_Call_Info", action = "http://tempuri.org/Get_Call_Info")
    @WebResult(name = "Get_Call_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Call_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCallInfo")
    @ResponseWrapper(localName = "Get_Call_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCallInfoResponse")
    public String getCallInfo(
        @WebParam(name = "strSdate", targetNamespace = "http://tempuri.org/")
        String strSdate,
        @WebParam(name = "strEdate", targetNamespace = "http://tempuri.org/")
        String strEdate,
        @WebParam(name = "strCaller", targetNamespace = "http://tempuri.org/")
        String strCaller,
        @WebParam(name = "strExt", targetNamespace = "http://tempuri.org/")
        String strExt,
        @WebParam(name = "strCallid", targetNamespace = "http://tempuri.org/")
        String strCallid,
        @WebParam(name = "strGhid", targetNamespace = "http://tempuri.org/")
        String strGhid);

    /**
     * 
     * @param strCallid
     * @param strDate
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Get_Rec_FTP_Info", action = "http://tempuri.org/Get_Rec_FTP_Info")
    @WebResult(name = "Get_Rec_FTP_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Get_Rec_FTP_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecFTPInfo")
    @ResponseWrapper(localName = "Get_Rec_FTP_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRecFTPInfoResponse")
    public String getRecFTPInfo(
        @WebParam(name = "strCallid", targetNamespace = "http://tempuri.org/")
        String strCallid,
        @WebParam(name = "strDate", targetNamespace = "http://tempuri.org/")
        String strDate);

    /**
     * 
     * @param strAgentInfoNew
     * @param strAgentInfoSrc
     * @param nEditType
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Edit_Agent_Info", action = "http://tempuri.org/Edit_Agent_Info")
    @WebResult(name = "Edit_Agent_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Edit_Agent_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditAgentInfo")
    @ResponseWrapper(localName = "Edit_Agent_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditAgentInfoResponse")
    public int editAgentInfo(
        @WebParam(name = "strAgentInfo_New", targetNamespace = "http://tempuri.org/")
        String strAgentInfoNew,
        @WebParam(name = "strAgentInfo_Src", targetNamespace = "http://tempuri.org/")
        String strAgentInfoSrc,
        @WebParam(name = "nEditType", targetNamespace = "http://tempuri.org/")
        int nEditType);

    /**
     * 
     * @param strACDGroupNew
     * @param strACDGroupSrc
     * @param nEditType
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Edit_ACD_Group_Info", action = "http://tempuri.org/Edit_ACD_Group_Info")
    @WebResult(name = "Edit_ACD_Group_InfoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Edit_ACD_Group_Info", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditACDGroupInfo")
    @ResponseWrapper(localName = "Edit_ACD_Group_InfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditACDGroupInfoResponse")
    public int editACDGroupInfo(
        @WebParam(name = "strACD_Group_New", targetNamespace = "http://tempuri.org/")
        String strACDGroupNew,
        @WebParam(name = "strACD_Group_Src", targetNamespace = "http://tempuri.org/")
        String strACDGroupSrc,
        @WebParam(name = "nEditType", targetNamespace = "http://tempuri.org/")
        int nEditType);

    /**
     * 
     * @param nMagType
     * @param strACDGPMemSrc
     * @param strACDGPMemNew
     * @return
     *     returns int
     */
    @WebMethod(operationName = "Mag_ACDGP_Member", action = "http://tempuri.org/Mag_ACDGP_Member")
    @WebResult(name = "Mag_ACDGP_MemberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Mag_ACDGP_Member", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MagACDGPMember")
    @ResponseWrapper(localName = "Mag_ACDGP_MemberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MagACDGPMemberResponse")
    public int magACDGPMember(
        @WebParam(name = "strACDGPMem_New", targetNamespace = "http://tempuri.org/")
        String strACDGPMemNew,
        @WebParam(name = "strACDGPMem_Src", targetNamespace = "http://tempuri.org/")
        String strACDGPMemSrc,
        @WebParam(name = "nMagType", targetNamespace = "http://tempuri.org/")
        int nMagType);

}
